### ISSUE TITLE
BUG: /export path results in error

### ISSUE THREAD

**Issue by jackahl** [kitconcept/volto-blocks#118]
Version: 10.1.1

Description:
When adding /export to the end of a page url, it does not export any json. Instead it throws error 500 with console traceback:
```
TypeError: Cannot read property 'dispatch' of undefined

  20 |   res.set('Content-Type', 'application/json');
  21 |
> 22 |   store
  23 |     .dispatch(getContent(req.path.replace('/export', '')))
  24 |     .then((content) => {
  25 |       return new Promise(function (resolve, reject) {

    at jsonExporter (/Users/jakobkahl/workspace/fzj-internet/src/addons/kitconcept.volto-blocks/src/server.js:22:1)
    at Layer.handle [as handle_request] (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/index.js:281:22
    at param (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/jakobkahl/workspace/fzj-internet/node_modules/express/lib/router/index.js:410:3)
```

**Comment by sneridagh** [comment]
@jackahl did we fix this?

**Comment by davisagli** [comment]
@sneridagh There's a good chance this was the same issue as #145 -- Let's close it and it will become clear if we need to revisit it.
